# Generated by Django 3.2.16 on 2022-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='second_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='third_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
